[project]
name = "xtsci-function"
version = "0.0.1"
description = "Function class and trial functions"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]
license = "MIT"
license-file = "LICENSE"
readme = "readme.org"
repository = "https://github.com/HaoZeke/xtsci-function"

[tasks]

[dependencies]
python = "3.10.*"
matplotlib = "3.8.2.*"
fmt = "10.1.1.*"
cmake = "3.25.1.*"
ninja = "1.11.1.*"
cppcheck = "2.12.1.*"
numpy = "1.26.2.*"
xtensor-io = "0.13.0.*"
zlib = "1.2.13.*"
pip = "23.3.1.*"
adjustText = "0.7.3.1.*"
scipy = "1.11.4.*"
xtensor = "0.24.7.*"
meson = "1.3.0.*"
pkg-config = "0.29.2.*"
sympy = "1.12.*"
packaging = "23.2.*"
cmcrameri = "1.7.*"
cpplint = "1.6.0.*"
xtensor-blas = "0.20.0.*"
ipython = "8.18.1.*"
xtensor-python = "0.26.1.*"
catch2 = "3.4.0.*"
towncrier = "23.11.0.*"
