* About ~xtsci-function~

A repository with a function base class for ease of exploration, with optimizers
and saddle search methods. The repository also includes standard test functions
from statistics and chemistry.

Trial functions implemented:
- Rosenbrock function
- Himmelblau's function

** Usage
Until bindings are ready, ~tiny_cli.cpp~ can be edited and run with output piped
to get a visual for the trial functions.

#+begin_src bash
meson setup bbdir
meson compile -C bbdir
./bbdir/CppCore/tiny_cli > output.txt
#+end_src

** Components
The heart of the library is the ~xts::func~ namespace.

- Note that this uses designated initializers, a C++20 feature.

** Tests

For the most part these are computed using reference implementations in ~R~, from which ~numericDeriv~ is used to .

** Provenance
References are provided, but these were originally conceived for use with
[[https://github.com/HaoZeke/xtsci-optimize][xtsci-optimize]]. Most of these are derived from the work of [[https://www.sfu.ca/~ssurjano/index.html][Surjanovic and
Bingham]] (Virtual Library of Simulation Experiments).

** License
MIT.
